version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mobile-boilerplate-db
    environment:
      POSTGRES_DB: mobile_app_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mobile-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: mobile-boilerplate-backend
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mobile_app_dev
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - mobile-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  mobile-network:
    driver: bridge